# Generated by Django 4.2.25 on 2025-10-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sis_app.person')),
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            bases=('sis_app.person',),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sis_app.subject')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sis_app.student')),
            ],
            options={
                'unique_together': {('reg_no', 'subject_code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_classes', models.IntegerField(default=0)),
                ('attended_classes', models.IntegerField(default=0)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='sis_app.enrollment')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('credit_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='sis_app.enrollment')),
            ],
        ),
    ]
