# Generated by Django 5.1.3 on 2025-10-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sis_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
