# Generated by Django 5.1.3 on 2025-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sis_app", "0002_student_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
